apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: profile
spec:
  ports:
    - port: 3306
  selector:
    app: profile
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: profile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: profile
spec:
  selector:
    matchLabels:
      app: profile
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: profile
        tier: mysql
    spec:
      containers:
      - image: mysql/mysql-server:8.0.20
        name: mysqldb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: profiles
        args: ["--default-authentication-plugin=mysql_native_password"]            
        ports:
        - containerPort: 3306
          name: mysqldb
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim