apiVersion: v1
kind: Service
metadata:
  name: profile
  labels:
    app: profile-app
spec:
  ports:
    - port: 8080
  selector:
    app: profile-app
    tier: backend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-image-pv-claim
  labels:
    app: profile-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: profile
  labels:
    app: profile-app
spec:
  selector:
    matchLabels:
      app: profile-app
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: profile-app
        tier: backend
    spec:
      containers:
      - image: leandrosantos/profile-mvc:latest
        name: profile
        ports:
        - containerPort: 8080
          name: profile
        volumeMounts:
          - name: profile-image-persistent-storage
            mountPath: /tmp
      volumes:
      - name: profile-image-persistent-storage
        persistentVolumeClaim:
          claimName: profile-image-pv-claim
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: profile-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: profile
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
status:
  observedGeneration: 1
  lastScaleTime: "2020-06-11T15:33:30Z"
  currentReplicas: 1
  desiredReplicas: 1
  conditions: []
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0